SPLIT_TRAIN_TEST_COMPONENT = 'split_train_test_component'
PREPROCESS_COMPONENT = 'preprocess_component'
INDEXING_COMPONENT = 'indexing_component'
BATCHING_COMPONENT = 'batching_component'
MAGIC_COMPONENT = 'magic_component'

GLOBAL = 'global'
GLOBAL_DIRECTOR = 'tmp_dir'
GLOBAL_HPARAMS = 'hparams'
GLOBAL_OUTPUT = 'output_dir'
GLOBAL_NUM_CLASSES = 'num_classes'
