INITIAL_TRANSFORM = 'initial_transform'
PREPROCESS_TRANSFORM = 'preprocess_transform'
INDEXING_TRANSFORM = 'indexing_transform'
BATCHING_TRANSFORM = 'batching_transform'
MAGICAL_TRANSFORM = 'magical_transform'
GLOBAL = 'global'
GLOBAL_DIRECTOR = 'tmp_dir'
GLOBAL_HPARAMS = 'hparams'
